# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pre-release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "CI"
          git fetch
      - run: npm i
      - run: npm run release -- --prerelease rc
      - run: |
          git push
          git push origin --tags

  build:
    needs: update-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.ref}}
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: npm run build --if-present
    - run: |
        cp ./package.json ./dist
        cp ./readme.md ./dist
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: ./dist


  npm-publish:
    needs: update-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - uses: actions/download-artifact@v1
      with:
        name: build
    - run: npm publish --tag rc
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
