
name: release

on:
    milestone:
      types: [closed]

      jobs:
        update-version:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v2
            with:
              fetch-depth: 0
            - uses: actions/setup-node@v1
              with:
                node-version: 12
            - run: |
                git config --global user.email "you@example.com"
                git config --global user.name "CI"
                git fetch
            - run: npm i
            - run: npm run release
            - run: |
                git push
                git push origin --tags
      
        build:
          needs: update-version
          runs-on: ubuntu-latest
          steps:
          - uses: actions/checkout@v2
            with:
              ref: ${{github.ref}}
          - uses: actions/setup-node@v1
            with:
              node-version: 12
              registry-url: https://registry.npmjs.org/
          - run: npm ci
          - run: npm run build --if-present
          - run: |
              cp ./package.json ./dist
              cp ./readme.md ./dist
          - uses: actions/upload-artifact@v1
            with:
              name: build
              path: ./dist
      
      
        npm-publish:
          needs: build
          runs-on: ubuntu-latest
          steps:
          - uses: actions/setup-node@v1
            with:
              node-version: 12
              registry-url: https://registry.npmjs.org/
          - uses: actions/download-artifact@v1
            with:
              name: build
          - run: npm publish --tag latest
            env:
              NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      